### ISSUE TITLE
Add output catalog that matches diaSrc catalog to diaObject

### ISSUE THREAD

**Issue by rearmstr** [LSSTDESC/dia_pipe#1]
It is useful to know which diaSrc match to which diaObject.  This ticket would add an additional output product per ccd that would have which diaSrc was matched to which diaObject.

**Comment by rearmstr** [comment]
@wmwv In trying to work on this issue, I realized that at the time when I have the matches for each diaSrc to each diaObject, I only have them for those that overlap the particular patch I am processing.  This is because I am doing the parallelization across patches.  

One option to deal with this is to write an id file per patch.  Each id file should contain a unique set of objects so combining them all should get the original set of objects.  This step could be part of the dia pipeline.  Do you see any problems with this approach?

**Comment by wmwv** [comment]
@rearmstr This solution of one id file per patch seems fine to me.

Is this the solution you went with?

**Comment by rearmstr** [comment]
Yes, I have implemented this option on the current branch and it seems to be a good solution.  The one issue is that it requires pyarrow or fastparquet neither of which is available in the stack.

**Comment by wmwv** [comment]
I will be submitting an RFC to add `pyarrow` to `lsst_distrib` later today.

**Comment by rearmstr** [comment]
Great, than it hopefully won't be an issue.

**Comment by slosar** [comment]
Is this now done as per quarterly report? If so, close the ticket.
