### ISSUE TITLE
Forced photometry algorithm fluxes are very different from non-forced

### ISSUE THREAD

**Issue by rearmstr** [LSSTDESC/dia_pipe#13]
Bruno found that the forced photometry fluxes were several magnitudes away from the diaSrc fluxes.  Here is an example plot.

![image](https://user-images.githubusercontent.com/1485496/82095825-b731df00-96b4-11ea-9809-c98a43a6f73d.png)

**Comment by rearmstr** [comment]
After some debugging I found that some of the forced algorithms are using a `getExposure` function that is being inherited from one of the base classes and thus not getting the right image.

**Comment by wmwv** [comment]
👏
