### ISSUE TITLE
Average calibrated fluxes for diaObjects

### ISSUE THREAD

**Issue by rearmstr** [LSSTDESC/dia_pipe#2]
When the diaObjects are created it does simple averages from the diaSrc catalogs.  However, these include uncalibrated fluxes.  This ticket would be to have a special case to average fluxes such that it uses calibrated versions.

This also may be related to applying calibrations from something like joint-cal to get accurate photometry and astrometry.

**Comment by wmwv** [comment]
The averages should also be separated per-band.

**Comment by slosar** [comment]
Is this now done as per quarterly report? If so, close the ticket.
